hys:
  mongodb:
    comment:
      uri: mongodb://test:test123@43.250.238.41/
      dataBase: comment
    exam:
      uri: mongodb://exam:exam123@43.250.238.41/
      dataBase: exam

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka:8761/eureka/ #指定服务注册中心的地址  http://localhost:8761/eureka/ localhost

spring:
  profiles:
    active: dev
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/doctor?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&testOnBorrow=true&testWhileIdle=true&serverTimezone=GMT%2B8 #jdbc:mysql://47.90.97.90:3306/csj?characterEncoding=UTF-8
    username: root
    password: happyday1311
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
rmjk:
  msgService: http://43.250.238.9:8086/msg
redis:
  #Redis主机
  host: 127.0.0.1
  #端口
  port: 6379
  #密码iTek123456
  password: 12345
  #使用的数据库编号 10
  database: 0
  #客户端超时时间单位是毫秒 默认是2000
  timeout: 2000
  #最大空闲数
  maxIdle: 300
  #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
  maxActive: 48
  #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
  maxTotal: 48
  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWaitMillis: 1000
  #连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
  #每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 1024
  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
  #在空闲时检查有效性, 默认false
  testWhileIdle: true
  #redis集群配置
  #spring.redis.cluster.nodes=192.168.177.128:7001,192.168.177.128:7002,192.168.177.128:7003,192.168.177.128:7004,192.168.177.128:7005,192.168.177.128:7006
  #spring.redis.cluster.max-redirects=3
  #哨兵模式
  #redis.sentinel.host1=192.168.177.128
  #redis.sentinel.port1=26379
  #redis.sentinel.host2=172.20.1.231
  #redis.sentinel.port2=26379
swagger:
  enable: true